# fly.toml app configuration file generated for factorio-server-holy-cherry-5608 on 2025-08-26T19:45:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'factorio-server-holy-cherry-5608'
primary_region = 'lhr'

[build]

[env]
  DLC_SPACE_AGE = 'true'
  GENERATE_NEW_SAVE = 'false'
  LOAD_LATEST_SAVE = 'true'
  SAVE_NAME = '_autosave1'

[http_service]
  internal_port = 34197
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = 34197

  [[services.ports]]
    port = 34197

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
